XBotInterface:
  urdf_path: $PWD/kyon_real_wheels_no_yaw.urdf
  srdf_path: $PWD/kyon_real_wheels_no_yaw.srdf

ModelInterface:
  model_type: pin
  is_model_floating_base: true

# defaults
motor_pd:
  "hip_roll*": [1000, 10]
  "hip_pitch*": [1000, 10]
  "knee_pitch*": [1000, 10]
  "ankle_yaw*": [800, 10]
  "wheel_joint*": [0, 30]

# startup pd config
startup_motor_pd:
  "hip_roll*": [100, 40]
  "hip_pitch*": [100, 40]
  "knee_pitch*": [100, 40]
  "ankle_yaw*": [800, 10]
  "wheel_joint*": [0, 30]
  
# hal
xbotcore_device_configs:
    sim: $PWD/hal/kyon_gz.yaml
    dummy: $PWD/hal/kyon_dummy.yaml

# threads
xbotcore_threads:
    rt_main:  {sched: fifo , prio: 60, period: 0.001}
    nrt_main: {sched: other, prio: 0 , period: 0.005}

# plugins
xbotcore_plugins:

    homing:
        thread: rt_main
        type: homing

    ros_io: {thread: nrt_main, type: ros_io}

    ros_control: {thread: nrt_main, type: ros_control, params: {autostart: {type: bool, value: true}}}

# global parameters
xbotcore_param:
  /xbot/hal/joint_safety/filter_autostart: {value: true, type: bool}
  # /xbot/hal/joint_safety/filter_cutoff_hz: {value: 1.0, type: double}
  /xbot/hal/joint_safety/filter_safe_cutoff_hz: {value: 5.0, type: double}
  /xbot/hal/joint_safety/filter_medium_cutoff_hz: {value: 40.0, type: double}
  /xbot/hal/joint_safety/filter_fast_cutoff_hz: {value: 60.0, type: double}
  /xbot/hal/joint_safety/delta_check_dt: 0.05
  /xbot/hal/enable_safety: {value: true, type: bool}
