[tool.poetry]
name = "kyonrlstepping"
version = "0.1.0"
description = ""
authors = ["Andrea Patrizi <andreapatrizi1b6e6@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
