# defaults
motor_pd:
  hip_roll*: [500, 60]
  hip_pitch*: [500, 60]
  knee_pitch*: [500, 60]
  wheel_joint*: [0, 30]

# startup pd config
startup_motor_pd:
  hip_roll*: [400, 30]
  hip_pitch*: [400, 30]
  knee_pitch*: [400, 30]
  wheel_joint*: [0, 30]