# defaults
motor_pd:
  "hip_roll*": [200, 60]
  "hip_pitch*": [200, 60]
  "knee_pitch*": [200, 60]
  "wheel_joint*": [0, 30]

# startup pd config
startup_motor_pd:
  "hip_roll*": [100, 10]
  "hip_pitch*": [100, 10]
  "knee_pitch*": [100, 10]
  "wheel_joint*": [0, 30]