# defaults
motor_pd:
  hip_roll*: [200, 60]
  hip_pitch*: [200, 60]
  knee_pitch*: [200, 60]
  wheel_joint*: [0, 30]

# startup pd config
startup_motor_pd:
  hip_roll*: [100, 30]
  hip_pitch*: [100, 30]
  knee_pitch*: [100, 30]
  wheel_joint*: [0, 30]