XBotInterface:
  urdf_path: $PWD/xmj_env_files/kyon.urdf
  srdf_path: $PWD/xmj_env_files/kyon.srdf

# defaults
motor_pd:
  "hip_roll*": [400, 20]
  "hip_pitch*": [400, 20]
  "knee_pitch*": [400, 20]
  "wheel_joint*": [0, 30]

# startup pd config
startup_motor_pd:
  "hip_roll*": [400, 20]
  "hip_pitch*": [400, 20]
  "knee_pitch*": [400, 20]
  "wheel_joint*": [0, 30]