motor_pd:
  j_arm*_1: [500, 10]
  j_arm*_2: [500, 10]
  j_arm*_3: [500, 10]
  j_arm*_4: [500, 10]
  j_arm*_5: [100, 5]
  j_arm*_6: [100, 5]
  j_arm*_7: [100, 5]
  hip_yaw_*: [3000, 30]
  hip_pitch_*: [3000, 30]
  knee_pitch_*: [3000, 30]
  ankle_pitch_*: [1000, 10]
  ankle_yaw_*: [300, 10]
  neck_pitch: [10, 1]
  neck_yaw: [10, 1]
  torso_yaw: [1000, 30]
  j_wheel_*: [0, 30]