# defaults
motor_pd:
  hip_roll*: [800, 80]
  hip_pitch*: [800, 80]
  knee_pitch*: [800, 80]
  wheel_joint*: [0, 30]

# startup pd config
startup_motor_pd:
  hip_roll*: [800, 80]
  hip_pitch*: [800, 80]
  knee_pitch*: [800, 80]
  wheel_joint*: [0, 30]